# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Create ZIP archive
        run: |
          zip -r agencyq-utilities-sif.zip . -x ".gitignore" ".git/*" ".github/*"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: agencyq-utilities-sif.zip
        run: |
          git tag ${{ steps.tag_version.outputs.version_tag }}
          git push origin ${{ steps.tag_version.outputs.version_tag }}
